### PR TITLE
Basic Project Structure.

### PR DESCRIPTION
**Pull request by DylanPKing**
- [ ] Code

 This PR is setting the basic project structure, and declaring interfaces for the core entities of this project. These will be subject to change as the project develops.

### CODE REVIEW

**Review by SzymonSztyrmer — APPROVED** [review]
LGTM

**Comment by Bmalone100** [comment]
>  @`
doge
`

**Review by SzymonSztyrmer — APPROVED** [review]
LGTM

**Review by LouiseMadden — APPROVED** [review]
Looks good :)

**Review by Bmalone100 — COMMENTED** [review]
Looking good.

**Pull request merged**
