### PR TITLE
fixed some the code smells that were shown by SonarQube

### PR DESCRIPTION
**Pull request by SzymonSztyrmer**
Fixed the following:

- Cognitive Complexity lowered from 17 to 7 and 10 in 2 separate functions.
- Repeated use of a String turned into a constant
- All switch cases now have a default case
- GetAttributtes now returns a HashMap instead of the Map generic
- Abstract classes for races now have a protected constructor
- variable "properties" in all weapon helper files now renamed to "propertiesList"

### CODE REVIEW

**Review by Bmalone100 — APPROVED** [review]
LGTM, random updates to xml files though, good ol' IntelliJ

**Review by SzymonSztyrmer — COMMENTED** [review]
You know, I deliberately excluded the xml stuff from my commit and it got added anyway?

**Review by DylanPKing — APPROVED** [review]
LGTM

**Review by LouiseMadden — APPROVED** [review]
LGTM

**Pull request merged**
